### ISSUE TITLE
Undefined variable $records db_conn.php on line 73

### ISSUE THREAD

**Issue by mudrd8mz** [SE-Stuttgart/kib3_moodleplugin_srg#3]
I am getting quite a few of warnings - see screenshot attached below. Please refer to: https://docs.moodle.org/dev/Plugin_contribution_checklist#Functionality

By the way, as I read it, the `build_DB_table()` is actually performing DB queries inside foreach loop. That's a well known performance killer and something to be avoided at almost all cost generally. 

![image](https://github.com/SE-Stuttgart/kib3_moodleplugin_srg/assets/85831/becd6471-170a-4cbf-8112-b8afa14a7061)

**Comment by danmarsden** [comment]
as mentioned in https://tracker.moodle.org/browse/CONTRIB-9198 the way you have wrapped the standard Moodle DB functions in a wrapper makes this extremely hard to check against sql injection vulnerabilities - it would be preferable to delete this file and use standard Moodle DB apis directly in your code instead of calling your wrapper.

**Comment by MakinZeel** [comment]
Thanks for the feedback.
As mentioned in the commit it still uses a Wrapper. It seemed to me the simplest method with the different requirements of the multiple desired tables, that include nested db-requests based on the 'objecttable' column of the first db-request.
But I reworked it, so that it has less db requests: every function in db_sql.php now calls every required db-table only once.
